CREATE DATABASE springmvc_auth;
use springmvc_auth;

# 用户表
CREATE TABLE TB_USERS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(200) NOT NULL
);

# 角色表
CREATE TABLE TB_ROLES (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(200) NOT NULL
);

# 权限表
CREATE TABLE TB_AUTHS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(200)
);

# 用户角色关系表
CREATE TABLE TB_USER_ROLE (
  ROLE_ID INT,
  USER_ID INT
);

# 角色权限关系表
CREATE TABLE TB_ROLE_AUTH (
  ROLE_ID INT,
  AUTH_ID INT
);

# 用户权限关系表
CREATE TABLE TB_USER_AUTH (
  USER_ID INT,
  AUTH_ID INT
);